# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 情報、知識、経験の足跡
email: gyo@re-work.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blueplanet42.info" # the base hostname & protocol for your site
twitter_username: blueplanet42
github_username:  blueplanet

# Build settings
markdown: kramdown
